---
swagger: "2.0"
info:
  description: "AI Customer Service application, built during the Cloud and Big Data\
    \ course at Columbia University."
  version: "1.0.0"
  title: "AI Customer Service API"
host: "bwljxqvyx5.execute-api.us-east-1.amazonaws.com"
basePath: "/s1"
schemes:
- "https"
paths:
  /chatbot:
    post:
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/BotResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
definitions:
  Message:
    type: "object"
    properties:
      type:
        type: "string"
      unstructured:
        $ref: "#/definitions/UnstructuredMessage"
  UnstructuredMessage:
    type: "object"
    properties:
      id:
        type: "string"
      text:
        type: "string"
      timestamp:
        type: "string"
        format: "datetime"
  BotResponse:
    type: "object"
    properties:
      messages:
        type: "array"
        items:
          $ref: "#/definitions/Message"
